#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running pre-commit checks..."

# Run lint-staged
npm run lint-staged

# Run tests
echo "🧪 Running tests..."
npm test --  --bail --findRelatedTests

echo "✅ Pre-commit checks passed!"
